SELECT * FROM EMP;

SELECT ENAME. SAL, SAL*12+COMM AS "연봉", COMM 
FROM EMP;

SELECT ENAME "성명", SAL "급여", SAL*12*COMM "연봉"
FROM EMP;

SELECT DEPTNO FROM EMP;
SELECT DISTINCT DPETINO FROM EMP;
SELECT JOB, DEPTNO FROM EMP;

SELECT * FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, JOB,SAL
FROM EMP
WHERE SAL>2500;

SELECT *
FROM EMP
WHERE SAL * 12 =3600;

SELECT ENAME
FROM EMP
WHERE SAL >= 2500 AND JOB = 'MANAGER'; 

SELECT EMPNO, ENAME, DEPTNO
FROM EMP;

SELECT ename || 'S JOB IS' || JOB AS EMPLOYEE
FROM EMP;
 --문제 1번
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';
--문제 2번
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';
--문제 3번
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE (DEPTNO = 20 OR DEPTNO = 30)
AND SAL > 2000;
--문재 4번
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL < 2000 OR SAL > 3000;
--문재 5번
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND ENAME LIKE '%E%'
AND (SAL < 1000 OR SAL > 2000);
--문제 6번
SELECT *
FROM EMP
WHERE COMM IS NULL
AND MGR IS NOT NULL
AND (JOB = 'MANAGER' OR JOB = 'CLERK')
AND SUBSTR(ENAME, 2, 1) <> 'L';

SELECT -10, ABS(-10)FROM dual;

SELECT SYSDATE FROM dual;

SELECT SYSDATE AS "현재시간",
    SYSDATE -1 AS "어제",
    SYSDATE +1 AS "어제"
    FROM dual;
    
SELECT SYSDATE AS "현재 날짜",
       ADD_MONTHS(SYSDATE, 6) AS "6개월 후 날짜"
FROM DUAL;

SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM,
    NVL(COMM,0),
    SAL+NVL(COMM,0)
FROM EMP;

SELECT EMPNO, ENAME, COMM,
    NVL2(COMM, 'O', 'X'),
    NVL2(COMM, SAL*12+COMM, SAL*12) AS "연봉"
FROM EMP;

--문제 1번
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

--문제 2번
SELECT *
FROM EMP
WHERE COMM IS NULL;

--문제 3번
SELECT *
FROM EMP
WHERE MGR IS NULL;

--문제 4번
SELECT *
FROM EMP
ORDER BY SALARY DESC;
 --문제 5번
SELECT *
FROM EMP
ORDER BY SAL DESC, NVL(COMM, 0) DESC;
--문제 6번
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM EMP
ORDER BY HIREDATE ASC;
--문재 7번
SELECT EMPNO, ENAME
FROM EMP
ORDER BY EMPNO DESC;
--문제8번
SELECT EMpNO, HIREDATE, ENAME, SAL
FROM EMP
ORDER BY DEPTNO ASC, HIREDATE DESC;
--문재 9번
SELECT SYSDATE FROM DUAL;
--문제 10번
SELECT EMPNO, ENAME, FLOOR(SAL/100)*100 AS "임금"
FROM EMP
ORDER BY SAL DESC;
--문제 11번
SELECT *
FROM EMP
WHERE MOD(EMpNO, 2) = 1;
--문제 12번
SELECT ENAME, TO_CHAR(HIREDATE, 'YYYY-MM') AS "입사일"
FROM EMP;
--문제 13번
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM') = '09';
--문재 14번
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = '1981';
--문재 15번
SELECT *
FROM EMP
WHERE ENAME LIKE '%E';
--문제 16번
SELECT *
FROM EMP
WHERE SUBSTR(ENAME, 3, 1) = 'R';
--문제 17번
SELECT EMPNO, ENAME, HIREDATE, ADDMONTHS(HIREDATE, 12*40) AS "40년 후 입사일"
FROM EMP;
--문제 18번
SELECT *
FROM EMP
WHERE MONTHS_BETWEEN(SYSDATE, HIREDATE) >= 12*38;
--문제 19번
SELECT TO_CHAR(SYSDATE, 'YYYY') AS "현재 년도"
FROM DUAL;





    




