SELECT * FROM EMP;

SELECT ENAME. SAL, SAL*12+COMM AS "¿¬ºÀ", COMM 
FROM EMP;

SELECT ENAME "¼º¸í", SAL "±Þ¿©", SAL*12*COMM "¿¬ºÀ"
FROM EMP;

SELECT DEPTNO FROM EMP;
SELECT DISTINCT DPETINO FROM EMP;
SELECT JOB, DEPTNO FROM EMP;

SELECT * FROM EMP
WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, JOB,SAL
FROM EMP
WHERE SAL>2500;

SELECT *
FROM EMP
WHERE SAL * 12 =3600;

SELECT ENAME
FROM EMP
WHERE SAL >= 2500 AND JOB = 'MANAGER'; 

SELECT EMPNO, ENAME, DEPTNO
FROM EMP;